version: '3.1'

services:
  db:
    image: postgres:11.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: heycar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: heycar

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080